---
title: "MK8WR"
author: "Greg Bedwell & Jessica Makofske"
date: "2023-05-10"
output: html_document
---

# libraries
```{r}
library(rvest)
library(ggplot2)
```

# functions
```{r}

lm_eqn <- function(etl){
  
    test <- etl
    m <- lm(get(test) ~ rmkd, dat);
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
}

```

# mk wr data
```{r}
page150 <- read_html("https://mkwrs.com/mk8dx/wrs.php")
page200 <- read_html("https://mkwrs.com/mk8dx/wrs_200.php")


# Times as of 05/10/2023
times150 <- html_table(page150, header = TRUE)[[2]]
times200 <- html_table(page200, header = TRUE)[[2]]

names <- times150$Track %>% unique()
write.table(x = names,
            file = "~/Desktop/names.txt",
            sep = "\t",
            quote = FALSE,
            row.names = FALSE,
            col.names = TRUE)

ltimes <- list( times150, times200 )

ltimes <- lapply( X = ltimes,
                  FUN = function(x){
                    x %>%
                      dplyr::select("Track", "Time+Video", "Character", "Vehicle", "Tires", "Glider") %>%
                      dplyr::mutate( `Time+Video` = gsub("'", ":", `Time+Video` ),
                                     `Time+Video` = gsub("\"", ":", `Time+Video` ) ) %>%
                      tidyr::separate( col = `Time+Video`, into = c( "min", "sec", "ms" ), sep = ":" ) %>%
                      dplyr::mutate( min = as.numeric( min ),
                                     sec = as.numeric( sec ),
                                     ms = as.numeric( ms ),
                                     time = ( 60 * min ) + ( sec ) + ( ms / 1000 ) ) %>%
                      dplyr::select( "Track", "time", "Character", 
                                     "Vehicle", "Tires", "Glider" ) %>%
                      magrittr::set_colnames( c( "track", "time", "character", 
                                                 "vehicle", "tires", "glider" ) ) %>%
                      tidyr::drop_na() %>%
                      dplyr::arrange( time ) %>%
                      dplyr::mutate( fold = time / max( time ) )
                    }
                  )

ltimes <- Map(cbind, ltimes, cc = c( 150, 200 ) )

```

```{r}

timesdf <- do.call( rbind, ltimes ) %>%
  dplyr::select( track, fold, cc ) %>%
  unique() %>%
  dplyr::select( track, fold ) %>%
  dplyr::group_by( track ) %>%
  dplyr::summarise( meanf = mean( fold ) ) %>%
  dplyr::arrange( meanf ) %>%
  dplyr::mutate( mean.rank = dplyr::row_number(),
                 rmkd = 500 * meanf )

```

# empirical time trials data
```{r}
tl_path <- "https://docs.google.com/spreadsheets/d/1zc1Cr6CvBePbThSM1Wp4LihRTJx2lZg7m_ee7Ftd0u8/edit?usp=sharing"

tl_html <- read_html(tl_path)

# Track length by time trials (10 times) 
etl <- html_table(tl_html, header = TRUE)[[1]]

# format
etl <- etl[,-1]
names(etl) <- as.character(etl[1,])
etl <- etl[-1,]

etl <- etl[,c("track", "cup", "etl_jess", "etl_nathan","baby_park_center_jess",  "baby_park_center_nathan")]

etl <- etl %>%
  dplyr::filter(!is.na(track)) %>%
  dplyr::filter(track != "")

etl[["etl_jess"]] <- as.numeric(etl[["etl_jess"]])
etl[["etl_nathan"]] <- as.numeric(etl[["etl_nathan"]])
etl[["baby_park_center_jess"]] <- as.numeric(etl[["baby_park_center_jess"]])
etl[["baby_park_center_nathan"]] <- as.numeric(etl[["baby_park_center_nathan"]])

# calculate norm data
## baby_park_center
### mean of jess and nathan's baby park center estimates
baby_park_center = (etl$baby_park_center_jess[!is.na(etl$baby_park_center_jess)] + etl$baby_park_center_nathan[!is.na(etl$baby_park_center_nathan)])/2

etl <- etl %>%
  dplyr::mutate(norm_jess = (etl_jess / etl_jess[track == "GCN Baby Park"])*baby_park_center,
                norm_nathan = (etl_nathan / etl_nathan[track == "GCN Baby Park"])*baby_park_center,
                etl = (norm_jess + norm_nathan)/2)


```

# join data and make linear model
```{r}
# join data
dat <- etl %>%
  dplyr::left_join(timesdf) %>%
  dplyr::filter(track != "GCN Baby Park")

d_min <- min(dat$rmkd)
d_max <- max(dat$rmkd)

# calc km from model
model_avg <- lm(etl ~ rmkd, data = dat)
model_jess <- lm(norm_jess ~ rmkd, data = dat)
model_nathan <- lm(norm_nathan ~ rmkd, data = dat)

dat <- dat %>%
  dplyr::mutate(ptl_avg = predict(model_avg, newdata = data.frame(rmkd = dat$rmkd)),
                ptl_jess = predict(model_jess, newdata = data.frame(rmkd = dat$rmkd)),
                ptl_nathan = predict(model_nathan, newdata = data.frame(rmkd = dat$rmkd)))

# write minimal table for export
dat_export <- dat %>%
  dplyr::select(track, cup, etl, ptl_avg, ptl_jess, ptl_nathan, rmkd)

# add regression line text

#make initial plot
p_avg <- dat %>%
  ggplot(aes(x = rmkd, y = etl)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlim(d_min-1,420)+
  ylim(1.5, 3.75)+
  xlab("RMKD (Relative Mario Kart Distance) \n in arbitrary units") +
  ylab("ETL (Empirical Track Length) \n in km") +
  geom_text(x = 300, y = 3.25, label = lm_eqn("etl"), parse = TRUE) +
  theme_bw(base_size = 16) +
  ggtitle("Average (Jess and Nathan) norm")

p_jess <- dat %>%
  ggplot(aes(x = rmkd, y = norm_jess)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlim(d_min-1,420)+
  ylim(1.5, 3.75)+
  xlab("RMKD (Relative Mario Kart Distance) \n in arbitrary units") +
  ylab("ETL (Empirical Track Length) \n in km") +
  geom_text(x = 300, y = 2.9, label = lm_eqn("norm_jess"), parse = TRUE) +
  theme_bw(base_size = 16) +
  ggtitle("Jess norm")

p_nathan <- dat %>%
  ggplot(aes(x = rmkd, y = norm_nathan)) +
  geom_point() +
  geom_smooth(method = "lm") +
  xlim(d_min-1,420)+
  ylim(1.5, 3.75)+
  xlab("RMKD (Relative Mario Kart Distance) \n in arbitrary units") +
  ylab("ETL (Empirical Track Length) \n in km") +
  geom_text(x = 300, y = 3.25, label = lm_eqn(etl = "norm_nathan"), parse = TRUE) +
  theme_bw(base_size = 16) +
  ggtitle("Nathan norm")
  

summary(model_avg)
summary(model_jess)
summary(model_nathan)
p_avg
p_jess
p_nathan

```

# export
```{r}

## greg originals
write.table(x = timesdf,
            file = "outs/MK8WR_rmkd.txt",
            sep = "\t",
            quote = FALSE,
            row.names = FALSE,
            col.names = TRUE)

openxlsx::write.xlsx(x = timesdf, file = "outs/MK8WR_rmkd.xlsx")


## jess outputs
ggsave("outs/lm_plot.png",p, width = 5, height = 4)

write.table(x = dat_export,
            file = "outs/mk8_export.txt",
            sep = "\t",
            quote = FALSE,
            row.names = FALSE,
            col.names = TRUE)

openxlsx::write.xlsx(x = timesdf, file = "outs/mk8_export.xlsx")
```


```{r}
sessionInfo()
```








































